services:
  mysqld:
    container_name: mysql
    image: mysql:9.0.0
    platform: linux/x86_64
    environment:
      TZ: Asia/Tokyo
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      MYSQL_DATABASE: test_db
      MYSQL_USER: test_db
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/conf.d:/etc/mysql/conf.d
      - ./mysql/init:/docker-entrypoint-initdb.d
    cap_add:
      - SYS_NICE
    ports:
      - "33060:3306"
    restart: always
